"""add actor attribution to crawl_texts and schedule_proposals

Revision ID: a8c4ad26f921
Revises: cc8cc5d6708a
Create Date: 2026-08-03 10:43:33.207704

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8c4ad26f921"
down_revision: Union[str, None] = "cc8cc5d6708a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("crawl_texts", sa.Column("created_by_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "crawl_texts", "users", ["created_by_id"], ["user_id"], ondelete="SET NULL"
    )
    op.add_column("schedule_proposals", sa.Column("updated_by_id", sa.UUID(), nullable=True))
    op.add_column("schedule_proposals", sa.Column("decided_by_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "schedule_proposals", "users", ["decided_by_id"], ["user_id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        None, "schedule_proposals", "users", ["updated_by_id"], ["user_id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "schedule_proposals", type_="foreignkey")
    op.drop_constraint(None, "schedule_proposals", type_="foreignkey")
    op.drop_column("schedule_proposals", "decided_by_id")
    op.drop_column("schedule_proposals", "updated_by_id")
    op.drop_constraint(None, "crawl_texts", type_="foreignkey")
    op.drop_column("crawl_texts", "created_by_id")
    # ### end Alembic commands ###
