server {
    listen 80;
    server_name suderhome.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name suderhome.com;

    ssl_certificate /etc/letsencrypt/live/suderhome.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/suderhome.com/privkey.pem;

    root /usr/share/nginx/html;

    location /auth {
        include /etc/nginx/snippets/proxy.conf;
        proxy_pass http://backend:8000;
    }
    location /users {
        include /etc/nginx/snippets/proxy.conf;
        proxy_pass http://backend:8000;
    }
    location /teams {
        include /etc/nginx/snippets/proxy.conf;
        proxy_pass http://backend:8000;
    }
    location /schedules {
        include /etc/nginx/snippets/proxy.conf;
        proxy_pass http://backend:8000;
    }
    location /crawl-texts {
        include /etc/nginx/snippets/proxy.conf;
        proxy_pass http://backend:8000;
    }
    location /schedule-proposals {
        include /etc/nginx/snippets/proxy.conf;
        proxy_pass http://backend:8000;
    }
    location /health {
        include /etc/nginx/snippets/proxy.conf;
        proxy_pass http://backend:8000;
    }

    location / {
        try_files $uri /index.html;
    }
}
